### ISSUE TITLE
Add opt-in hypothes.is

### ISSUE THREAD

**Issue by pkra** [pkra/peterkrautzberger.org#10]
To appease the gods akak @scoskey let's add a button next to the "email me" link that loads `//hypothes.is/embed.js` as a commenting system. Ideally, https://github.com/hypothesis/vision/issues/120 but what do I care ;-)

**Comment by scoskey** [comment]
can’t wait to see it in action.

**Comment by pkra** [comment]
You can already see it on boolesrings.org/krautzberger :-) (check the UI on the right edge of the viewport)

**Comment by scoskey** [comment]
Works for me. You have to create an account, but that can be said of many
comment systems.

On Mon, May 4, 2015 at 8:53 AM, Peter Krautzberger <notifications@github.com

**Comment by pkra** [comment]
It's been there for a loooong time. Maybe if there are no comments, people will notice ;-)
